version: '3'
services:
  app:
    build: .
    container_name: mcv-noti
    ports:
      - '6711:3000'
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    env_file:
      - ./.env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}/health']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
