version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres-mcv-noti
    ports:
      - '6710:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db-noti:/var/lib/postgresql/data
  app:
    build: .
    container_name: mcv-noti
    ports:
      - '6711:3000'
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    env_file:
      - ./.env
    depends_on:
      - postgres
volumes:
  postgres-db-noti:
