name: build image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/${OWNER_LC}/${{github.event.repository.name}}:${GITHUB_SHA}
          docker push ghcr.io/${OWNER_LC}/${{github.event.repository.name}}:${GITHUB_SHA}
