name: build image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner }}/${{github.event.repository.name}}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{github.event.repository.name}}:latest
